environment:
  matrix:
    - nodejs_version: 0.10.35

platform:
  - x64

shallow_clone: true

install:
  #- ps: Update-NodeJsInstallation $env:nodejs_version $env:Platform
  # http://help.appveyor.com/discussions/problems/618-nodejs-10030-doesnt-work-on-appveyor-cant-find-npm#comment_34002825
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - node --version
  - npm --version
  - SET PATH=%APPDATA%\npm;%PATH%
  - npm update -g npm
  - npm --version
  - node -e "console.log(process.arch);"
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - if "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - if "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - npm install --msvs_version=2013
#  - npm test
#  - .\scripts\test.bat

build: off
test: off
deploy:
  release: jest-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: $(GITHUB_TOKEN) # your encrypted token from GitHub
  artifact: /*/            # upload all NuGet packages to release assets
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
